Fix inline resolver for open api generator
micronaut-projects/micronaut-openapi pull request #1552
Opened 2024-04-24 11:39 UTC by altro3

2024-04-24 13:35 UTC, sdelamo requested changes
Can you add a PR description about what this change is about?

2024-04-24 13:35 UTC, sdelamo commented on openapi-generator/src/test/java/io/micronaut/openapi/generator/AbstractMicronautCodegenTest.java
> +//        output.deleteOnExit();
is this commented on purpose.

2024-04-24 13:48 UTC, altro3 commented on openapi-generator/src/test/java/io/micronaut/openapi/generator/AbstractMicronautCodegenTest.java
> +//        output.deleteOnExit();
fixed

2024-04-24 13:50 UTC, altro3 commented
> Can you add a PR description about what this change is about?

done

2024-04-25 05:02 UTC, sdelamo approved these changes

2024-04-25 05:02 UTC, merged