Add support generating Deprecated annotations and docs
micronaut-projects/micronaut-openapi pull request #1788
Opened 2024-09-25 11:27 UTC by altro3

Removed support swagger1 annotations for java generator

2024-09-30 13:21 UTC, sdelamo requested changes
removing swagger 1 annotations is a breaking change. 

Why are we mixing this removal with a PR to add Deprecated annotations?

2024-09-30 13:21 UTC, sdelamo commented on openapi-generator/src/test/java/io/micronaut/openapi/generator/AbstractMicronautCodegenTest.java
> +//        output.deleteOnExit();
```suggestion
        output.deleteOnExit();
```

2024-09-30 13:55 UTC, altro3 commented on openapi-generator/src/test/java/io/micronaut/openapi/generator/AbstractMicronautCodegenTest.java
> +//        output.deleteOnExit();
fixed

2024-09-30 13:59 UTC, altro3 commented
> removing swagger 1 annotations is a breaking change.
> 
> Why are we mixing this removal with a PR to add Deprecated annotations?

You are wrong, this change is not breaking. No one could generate code with swagger1 annotations before, simply because no one had the ability to change this setting (it is not passed in the plugin for gradle and maven).

In fact, this is just garbage that was left after moving the generator to this repository and this code was only in templates. By the way, in the generator for Kotlin, which I already wrote myself, there was no support for the first swagger.

I just removed the extra mouse, and this will not affect the previously generated code in any way.

2024-10-03 06:04 UTC, graemerocher approved these changes

2024-10-03 06:04 UTC, graemerocher commented
please resolve the conflicts

2024-10-03 07:12 UTC, altro3 commented
@graemerocher done

2024-10-10 07:44 UTC, graemerocher approved these changes

2024-10-10 07:44 UTC, merged