Do not use internal classes from micronaut-core
micronaut-projects/micronaut-openapi pull request #607
Opened 2021-11-03 09:37 UTC by ilopmar

Fixes #593

This PR removes the usage of Core's `@Internal` class `JavaClassElement`. We still have our own `JavaClassElementExt` but it doesn't extends from anything. That class has a lot of code copied from `JavaClassElement`because it is necessary to initialize the bean properties defined in a "fluent way" (like when using Lombok). See https://github.com/micronaut-projects/micronaut-core/pull/6415 for more information.
As suggested in that PR we could [explore another approach](https://github.com/micronaut-projects/micronaut-core/pull/6415#issuecomment-951079610) instead of adding another public method to `ClassElement`. We will explore that in the future, but at least, even with the code duplication here, we don't depend on the internal class anymore.

2021-11-03 14:06 UTC, graemerocher requested changes
probably and improvement but it still depends on `JavaMethodElement` which is internal API

2021-11-03 14:06 UTC, graemerocher commented on openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiIncludeVisitor.java
> +        ce.getEnclosedElements(ElementQuery.ALL_METHODS).forEach(method -> visitor.visitMethod(method, visitorContext));
This not filtering out static & private methods like the previous code

2021-11-03 15:59 UTC, ilopmar commented
I've added the missing filters (although I've duplicated the filter code in both places)

I missed the `JavaMethodElement`. It's not urgent because every time this has been broken has been because of `JavaClassElement`. In any case, I'll explore the approach suggested in the PR I sent to core. If we add the missing methods/filters/... to core to get the appropriate methods here, then we could get rid of completely of `JavaClassElementExt` in this module and use no internal classes.

2021-11-03 18:53 UTC, graemerocher commented
This is not quite what I meant, you need to use the `ElementQuery` API for the filtering, we can talk about it tomorrow

2021-11-04 11:17 UTC, graemerocher approved these changes

2021-11-04 14:53 UTC, merged