Fix incorrect processing of Iterable extended classes.
micronaut-projects/micronaut-openapi pull request #756
Opened 2022-06-25 15:10 UTC by altro3

Fixed #753

2022-06-28 16:54 UTC, graemerocher commented
Needs conflicts resolving. Thanks.

2022-06-29 10:17 UTC, altro3 commented
@graemerocher All conflicts resolved

2022-07-11 07:38 UTC, graemerocher requested changes

2022-07-11 07:38 UTC, graemerocher commented on openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
> +            boolean isHidden = fieldSchemaAnn != null && fieldSchemaAnn.get("hidden", Boolean.class).orElse(false);
can be simplified to:

```java
boolean isHidden = publicField.getAnnotationMetdata().booleanValue(Schema.class, "hidden").orElse(false)
```

2022-07-11 08:42 UTC, altro3 commented on openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
> +            boolean isHidden = fieldSchemaAnn != null && fieldSchemaAnn.get("hidden", Boolean.class).orElse(false);
@graemerocher fixed

2022-07-11 09:02 UTC, merged

2022-07-11 09:02 UTC, graemerocher commented
Thanks for the contribution!