Skip ignored headers
micronaut-projects/micronaut-openapi pull request #892
Opened 2022-12-29 12:00 UTC by altro3

2023-01-09 15:38 UTC, graemerocher requested changes
needs a test

2023-01-09 23:44 UTC, altro3 commented
@graemerocher done. Also merge PR #901, please

2023-01-10 07:50 UTC, graemerocher commented
tests failing

2023-01-10 08:35 UTC, altro3 commented
@graemerocher fixed

2023-01-17 08:57 UTC, merged